### ISSUE TITLE
Robust Arithmetic

### ISSUE THREAD

**Issue by michalkonecny** [michalkonecny/robust-plots#8]
## Details:
Hours Spent: 0

## Background
Enclosure arithmetic is needed to compute enclosures of functions given by formulas.

## Overview
Port relevant parts of module Approx from Haskell [CDAR](https://github.com/michalkonecny/cdar) including relevant tests.

## Acceptance Criteria
- [x] constants can be defined and printed (#9 )
- [x] field operations (+,-,*,/), are supported (#20 )
- [x] sqrt is supported
- [x] sine, cosine and pi are supported (#93)
- [x] exp, log and e are supported (#98)

## Closing Notes

Overview of changes can be found in PR _PR ID HERE_
